project:
  type: website
  output-dir: docs

website:
  title: "hpawig.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blogs.qmd

format:
  html:
    theme: morph
    linkcolor: "#9d20b7"
    css: styles.css
    toc: true