project:
  type: website
  output-dir: docs

website:
  title: "hpawig.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blogs.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true